apiVersion: v1
kind: Scenario
metadata:
  name: buzzer-passive
spec:
  condition: null
  action: terminate
  target: buzzer-passive
---
apiVersion: v1
kind: Package
metadata:
  label: null
  name: buzzer-passive
spec:
  pattern:
    - type: plain
  models:
    - name: buzzer-passive
      node: guest
      resources:
        volume:
        network:
---
apiVersion: v1
kind: Model
metadata:
  name: buzzer-passive
  annotations:
    io.piccolo.annotations.package-type: ba
    io.piccolo.annotations.package-name: ba
    io.piccolo.annotations.package-network: default
  labels:
    app: ba
spec:
  containers:
    - name: buzzer-passive
      image: localhost/kuksa-serial-bridge:latest
      env:
      - name: MASTER_IP
        value: "192.168.1.2"
      securityContext:
        privileged: true
      volumeMounts:
        - name: arduino
          mountPath: /dev/arduino_buzzer
  volumes:
    - name: arduino
      hostPath:
        path: /dev/arduino_passive
  terminationGracePeriodSeconds: 0
  restartPolicy: Always

