configs:
  vss_overlay.json:
    file: "./spec/vss.json"

services:
  failop-serial-bridge:
    build:
      context: ./serial
    image: failop-serial-bridge:latest
    container_name: failop-serial-bridge
    devices:
      - "/dev/arduino_joystick:/dev/arduino_joystick"
      - "/dev/arduino_led:/dev/arduino_led"
      - "/dev/arduino_gear:/dev/arduino_gear"
    volumes:
      - ./serial:/app
      - ./pullpiri-yaml/yaml:/yaml
    working_dir: /app
    command: python3 bridge.py
    environment:
      PYTHONUNBUFFERED: "1"
      MASTER_IP: "192.168.0.3"
    depends_on:
      - failop-databroker

  failop-databroker:
    image: "quay.io/eclipse-kuksa/kuksa-databroker:0.6.0"
    container_name: "failop-databroker"
    ports:
      - "55556:55555"
    configs:
      - "vss_overlay.json"
    environment:
      KUKSA_DATABROKER_ADDR: "0.0.0.0"
      KUKSA_DATABROKER_PORT: "55555"
      KUKSA_DATABROKER_METADATA_FILE: "/vss_overlay.json"
      RUST_LOG: "info"
    # for the time being, we do not use TLS secured connections to Databroker
    command: "--insecure"
