---
apiVersion: v1
kind: Scenario
metadata:
  name: led_timpani_test
spec:
  condition: null
  action: terminate
  target: led_timpani_test
---
apiVersion: v1
kind: Package
metadata:
  label: null
  name: led_timpani_test
spec:
  schedule: led_timpani_schedule
  pattern:
    - type: plain
  models:
    - name: guest-bridge
      node: guest
      resources:
        volume:
        network:
    - name: led_timpani_model
      node: guest
      resources:
        volume:
        network:
    - name: led_normal_model
      node: guest
      resources:
        volume:
        network:
---
apiVersion: v1
kind: Model
metadata:
  name: guest-bridge
  annotations:
    io.piccolo.annotations.package-type: led_timpani_test
    io.piccolo.annotations.package-name: led_timpani_test
    io.piccolo.annotations.package-network: default
  labels:
    app: guest-bridge
spec:
  containers:
    - name: kuksa-bridge-container
      image: localhost/failop-kuksa-bridge-guest:latest
  terminationGracePeriodSeconds: 0
  restartPolicy: Never
---
apiVersion: v1
kind: Model
metadata:
  name: led_timpani_model
  annotations:
    io.piccolo.annotations.package-type: led_timpani_test
    io.piccolo.annotations.package-name: led_timpani_test
    io.piccolo.annotations.package-network: default
  labels:
    app: led_timpani_model
spec:
  hostNetwork: true
  containers:
    - name: led_timpani
      image: localhost/led-timpani-controller:latest
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_NICE"]
      env:
        - name: BUSY_ITERATIONS
          value: "10000000"
      volumeMounts:
        - name: arduino-device
          mountPath: /dev/arduino_led_timpani
        - name: tmp-sync
          mountPath: /tmp
  volumes:
    - name: arduino-device
      hostPath:
        path: /dev/arduino_led_timpani
        type: CharDevice
    - name: tmp-sync
      hostPath:
        path: /tmp
        type: Directory
  terminationGracePeriodSeconds: 0
  restartPolicy: Never
---
apiVersion: v1
kind: Model
metadata:
  name: led_normal_model
  annotations:
    io.piccolo.annotations.package-type: led_timpani_test
    io.piccolo.annotations.package-name: led_timpani_test
    io.piccolo.annotations.package-network: default
  labels:
    app: led_normal_model
spec:
  hostNetwork: true
  containers:
    - name: led_normal
      image: localhost/led-normal-controller:latest
      securityContext:
        privileged: true
      env:
        - name: CPU_AFFINITY
          value: "10"
        - name: BUSY_ITERATIONS
          value: "10000000"
      volumeMounts:
        - name: arduino-normal-device
          mountPath: /dev/arduino_led_normal
        - name: tmp-sync
          mountPath: /tmp
  volumes:
    - name: arduino-normal-device
      hostPath:
        path: /dev/arduino_led_normal
        type: CharDevice
    - name: tmp-sync
      hostPath:
        path: /tmp
        type: Directory
  terminationGracePeriodSeconds: 0
  restartPolicy: Never
